image: adimit/docker-node-chromium:latest

stages:
  - setup
  - test
  - build
  - dist

# before_script:
#   - mkdir -p /cache/node_modules
#   - ln -s /cache/node_modules ${CI_PROJECT_DIR}/node_modules

npm:
  stage: setup
  script:
    - npm install
  tags:
    - node
  artifacts:
    paths:
      - node_modules

# karma:
#   stage: test
#   script:
#     - npm run test
#   tags:
#     - node
#     - chromium-headless

webpack:
  stage: build
  script:
    - ls -R node_modules
    - npm run build
#  only:
#    - master
  artifacts:
    paths:
      - addon

webext:
  stage: dist
  script:
    - ls -R addon
    - npm run dist
#  only:
#    - master
