image: adimit/docker-node-chromium:latest

stages:
  - setup
  - test
  - build
  - dist

cache:
  paths:
    - "./node-modules"

npm:
  stage: setup
  script:
    - npm install
  tags:
    - node

# karma:
#   stage: test
#   script:
#     - mkdir -p /cache/node_modules
#     - ln -s /cache/node_modules ${CI_PROJECT_DIR}/node_modules
#     - npm run test
#   tags:
#     - node
#     - chromium-headless

webpack:
  stage: build
  script:
    - ls -R node_modules
    - npm run build
  artifacts:
    paths:
      - addon
  tags:
    - node
#  only:
#    - master

webext:
  stage: dist
  script:
    - ls -R node_modules
    - npm run bundle
    - ls -R addon
  tags:
    - node
#  only:
#    - master
