image: adimit/docker-node-chromium:latest

stages:
  - setup
  - test
  - build
  - dist

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - "./node-modules"

npm:
  stage: setup
  script:
    - npm install
  tags:
    - node

karma:
  stage: test
  script:
    - npm run test
  tags:
    - node
    - chromium-headless

webpack:
  stage: build
  script:
    - ls -R node_modules
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - addon
  tags:
    - node
#  only:
#    - master

webext:
  stage: dist
  script:
    - ls -R node_modules
    - npm run bundle
    - ls -R addon
    - ls -R dist
  tags:
    - node
#  only:
#    - master
